---
- name: Installing Pacemaker Extra Tools
  yum:
    name: https://github.com/linux-ha-japan/pm_extra_tools/releases/download/pm_extra_tools-{{ pm_extra_tools_version.split('-').0 }}/pm_extra_tools-{{ pm_extra_tools_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm
    disable_gpg_check: true
- block:
    - set_fact:
        _s_lan_prefix: "{{ '%s/%s' | format(ansible_facts[s_lan_interface].ipv4.network, ansible_facts[s_lan_interface].ipv4.netmask) | ipaddr('prefix') }}"
        _d_lan_prefix: "{{ '%s/%s' | format(ansible_facts[d_lan_interface].ipv4.network, ansible_facts[d_lan_interface].ipv4.netmask) | ipaddr('prefix') }}"
    - name: Templating Resource Definition File
      template:
        src: ./pm_pcsgen_env.csv.j2
        dest: ./pm_pcsgen_env.csv
      register: _pm_pcsgen_env
    - name: Converting Resource Definition File to XML
      command:
        cmd: pm_pcsgen ./pm_pcsgen_env.csv
      when: _pm_pcsgen_env.changed
  when: ansible_hostname == groups.all.0
